const wordLibrary = [

  // 🐶 Animales (40)
  { word: "Perro", category: "Animal", hint: "Suele acompañar a humanos" },
  { word: "Gato", category: "Animal", hint: "Independiente y curioso" },
  { word: "Elefante", category: "Animal", hint: "Difícil de olvidar" },
  { word: "Delfín", category: "Animal", hint: "Le gusta saltar fuera del agua" },
  { word: "Águila", category: "Animal", hint: "Observa desde las alturas" },
  { word: "León", category: "Animal", hint: "Asociado al liderazgo" },
  { word: "Pingüino", category: "Animal", hint: "Elegante aunque torpe" },
  { word: "Tiburón", category: "Animal", hint: "Siempre en movimiento" },
  { word: "Caballo", category: "Animal", hint: "Históricamente útil para viajar" },
  { word: "Canguro", category: "Animal", hint: "Se desplaza de forma peculiar" },
  { word: "Lobo", category: "Animal", hint: "Suele moverse en grupo" },
  { word: "Oso", category: "Animal", hint: "Puede parecer tranquilo o peligroso" },
  { word: "Zorro", category: "Animal", hint: "Relacionado con la astucia" },
  { word: "Mono", category: "Animal", hint: "Muy expresivo" },
  { word: "Serpiente", category: "Animal", hint: "Se desliza sin hacer ruido" },
  { word: "Rana", category: "Animal", hint: "Pequeña pero llamativa" },
  { word: "Tigre", category: "Animal", hint: "Difícil de ignorar" },
  { word: "Vaca", category: "Animal", hint: "Asociada al campo" },
  { word: "Cerdo", category: "Animal", hint: "A menudo infravalorado" },
  { word: "Gallina", category: "Animal", hint: "Relacionada con lo cotidiano" },
  { word: "Cabra", category: "Animal", hint: "Se adapta a terrenos difíciles" },
  { word: "Oveja", category: "Animal", hint: "Suele seguir al grupo" },
  { word: "Ciervo", category: "Animal", hint: "Asociado a la elegancia" },
  { word: "Jirafa", category: "Animal", hint: "Destaca por encima del resto" },
  { word: "Hipopótamo", category: "Animal", hint: "Más peligroso de lo que parece" },
  { word: "Rinoceronte", category: "Animal", hint: "Fuerza concentrada" },
  { word: "Koala", category: "Animal", hint: "Vida tranquila" },
  { word: "Panda", category: "Animal", hint: "Aspecto inconfundible" },
  { word: "Camello", category: "Animal", hint: "Resiste condiciones duras" },
  { word: "Cebra", category: "Animal", hint: "Difícil de confundir" },
  { word: "Murciélago", category: "Animal", hint: "Activo cuando otros no" },
  { word: "Búho", category: "Animal", hint: "Relacionado con la sabiduría" },
  { word: "Halcón", category: "Animal", hint: "Velocidad precisa" },
  { word: "Pulpo", category: "Animal", hint: "Más inteligente de lo esperado" },
  { word: "Medusa", category: "Animal", hint: "Bonita pero peligrosa" },
  { word: "Langosta", category: "Animal", hint: "Caparazón resistente" },
  { word: "Cangrejo", category: "Animal", hint: "Movimiento poco directo" },
  { word: "Caracol", category: "Animal", hint: "Lleva su casa encima" },
  { word: "Hormiga", category: "Animal", hint: "Trabajo constante" },
  { word: "Abeja", category: "Animal", hint: "Pequeña pero clave" },

  // 🍕 Comida (40)
  { word: "Hamburguesa", category: "Comida", hint: "Suele comerse con las manos" },
  { word: "Sushi", category: "Comida", hint: "Pequeño pero elaborado" },
  { word: "Paella", category: "Comida", hint: "Se comparte fácilmente" },
  { word: "Chocolate", category: "Comida", hint: "Difícil parar con poco" },
  { word: "Ensalada", category: "Comida", hint: "Ligera pero variable" },
  { word: "Taco", category: "Comida", hint: "Puede ser desordenado" },
  { word: "Croqueta", category: "Comida", hint: "Pequeña sorpresa dentro" },
  { word: "Pizza", category: "Comida", hint: "Admite casi cualquier combinación" },
  { word: "Pasta", category: "Comida", hint: "Base con muchas variantes" },
  { word: "Helado", category: "Comida", hint: "Mejor en frío" },
  { word: "Pan", category: "Comida", hint: "Presente en muchas mesas" },
  { word: "Queso", category: "Comida", hint: "O lo amas o no tanto" },
  { word: "Arroz", category: "Comida", hint: "Muy versátil" },
  { word: "Pollo", category: "Comida", hint: "Muy común" },
  { word: "Pescado", category: "Comida", hint: "Viene de otro entorno" },
  { word: "Huevo", category: "Comida", hint: "Cambia mucho según cómo se haga" },
  { word: "Patata", category: "Comida", hint: "Se adapta a todo" },
  { word: "Sopa", category: "Comida", hint: "Reconfortante" },
  { word: "Bocadillo", category: "Comida", hint: "Práctico para llevar" },
  { word: "Tortilla", category: "Comida", hint: "Debate asegurado" },
  { word: "Lasaña", category: "Comida", hint: "Capas que esconden más" },
  { word: "Empanada", category: "Comida", hint: "Relleno protegido" },
  { word: "Gazpacho", category: "Comida", hint: "Frío pero intenso" },
  { word: "Churros", category: "Comida", hint: "Mejor en compañía" },
  { word: "Donut", category: "Comida", hint: "Forma reconocible" },
  { word: "Tarta", category: "Comida", hint: "Suele aparecer en celebraciones" },
  { word: "Galleta", category: "Comida", hint: "Pequeña tentación" },
  { word: "Yogur", category: "Comida", hint: "Suave y cotidiano" },
  { word: "Batido", category: "Comida", hint: "Se bebe más que se come" },
  { word: "Café", category: "Comida", hint: "Muchos lo necesitan" },
  { word: "Té", category: "Comida", hint: "Momento de calma" },
  { word: "Zumo", category: "Comida", hint: "Natural o no tanto" },
  { word: "Cereal", category: "Comida", hint: "Inicio del día" },
  { word: "Mermelada", category: "Comida", hint: "Dulce para untar" },
  { word: "Miel", category: "Comida", hint: "Hecha por otros" },
  { word: "Salchicha", category: "Comida", hint: "Procesado y popular" },
  { word: "Bacon", category: "Comida", hint: "Crujiente y sabroso" },
  { word: "Quesadilla", category: "Comida", hint: "Interior fundente" },
  { word: "Ramen", category: "Comida", hint: "Caliente y profundo" },
  { word: "Curry", category: "Comida", hint: "Aroma intenso" },

  // 🌍 Países (40)
  { word: "España", category: "País", hint: "Diversidad cultural" },
  { word: "Japón", category: "País", hint: "Tradición y tecnología" },
  { word: "Brasil", category: "País", hint: "Energía y ritmo" },
  { word: "Canadá", category: "País", hint: "Amplios paisajes" },
  { word: "Egipto", category: "País", hint: "Historia milenaria" },
  { word: "Australia", category: "País", hint: "Lejos de muchos" },
  { word: "Francia", category: "País", hint: "Influencia cultural" },
  { word: "Italia", category: "País", hint: "Tradición artística" },
  { word: "México", category: "País", hint: "Colores intensos" },
  { word: "Argentina", category: "País", hint: "Pasión característica" },
  { word: "China", category: "País", hint: "Gran escala" },
  { word: "India", category: "País", hint: "Diversidad enorme" },
  { word: "Alemania", category: "País", hint: "Organización" },
  { word: "Portugal", category: "País", hint: "Cercanía familiar" },
  { word: "Suecia", category: "País", hint: "Equilibrio social" },
  { word: "Noruega", category: "País", hint: "Naturaleza destacada" },
  { word: "Chile", category: "País", hint: "Forma particular" },
  { word: "Perú", category: "País", hint: "Raíces antiguas" },
  { word: "Grecia", category: "País", hint: "Origen de ideas" },
  { word: "Turquía", category: "País", hint: "Punto de encuentro" },
  { word: "Rusia", category: "País", hint: "Extensión enorme" },
  { word: "Estados Unidos", category: "País", hint: "Influencia global" },
  { word: "Reino Unido", category: "País", hint: "Historia y modernidad" },
  { word: "Irlanda", category: "País", hint: "Verde característico" },
  { word: "Suiza", category: "País", hint: "Neutralidad conocida" },
  { word: "Austria", category: "País", hint: "Elegancia clásica" },
  { word: "Bélgica", category: "País", hint: "Pequeño pero relevante" },
  { word: "Holanda", category: "País", hint: "Terreno especial" },
  { word: "Dinamarca", category: "País", hint: "Estilo de vida destacado" },
  { word: "Finlandia", category: "País", hint: "Frío y tranquilidad" },
  { word: "Polonia", category: "País", hint: "Historia compleja" },
  { word: "Hungría", category: "País", hint: "Centro europeo" },
  { word: "Tailandia", category: "País", hint: "Destino turístico" },
  { word: "Vietnam", category: "País", hint: "Contrastes culturales" },
  { word: "Corea del Sur", category: "País", hint: "Innovación constante" },
  { word: "Indonesia", category: "País", hint: "Muchas islas" },
  { word: "Nueva Zelanda", category: "País", hint: "Naturaleza pura" },
  { word: "Sudáfrica", category: "País", hint: "Diversidad marcada" },
  { word: "Marruecos", category: "País", hint: "Puerta cercana" },
  { word: "Colombia", category: "País", hint: "Ritmo y sabor" },

  // 🎬 Películas (40)
  { word: "Titanic", category: "Película", hint: "Final inevitable" },
  { word: "Avatar", category: "Película", hint: "Otro mundo" },
  { word: "Gladiator", category: "Película", hint: "Honor y venganza" },
  { word: "Frozen", category: "Película", hint: "Dejar ir" },
  { word: "Jurassic Park", category: "Película", hint: "La ciencia se complica" },
  { word: "Matrix", category: "Película", hint: "Nada es lo que parece" },
  { word: "Inception", category: "Película", hint: "Capas de realidad" },
  { word: "Interstellar", category: "Película", hint: "Más allá del tiempo" },
  { word: "Rocky", category: "Película", hint: "Superación personal" },
  { word: "Joker", category: "Película", hint: "Caída mental" },
  { word: "Batman", category: "Película", hint: "Oscuridad y justicia" },
  { word: "Superman", category: "Película", hint: "Poder y responsabilidad" },
  { word: "Spiderman", category: "Película", hint: "Vida doble" },
  { word: "Shrek", category: "Película", hint: "Rompe estereotipos" },
  { word: "Cars", category: "Película", hint: "Velocidad con personalidad" },
  { word: "Toy Story", category: "Película", hint: "Más de lo que parece" },
  { word: "Up", category: "Película", hint: "Viaje inesperado" },
  { word: "Coco", category: "Película", hint: "Recuerdos importantes" },
  { word: "Harry Potter", category: "Película", hint: "Destino marcado" },
  { word: "Star Wars", category: "Película", hint: "Conflicto constante" },
  { word: "The Godfather", category: "Película", hint: "Familia y poder" },
  { word: "Pulp Fiction", category: "Película", hint: "Historias cruzadas" },
  { word: "Fight Club", category: "Película", hint: "Identidad oculta" },
  { word: "Forrest Gump", category: "Película", hint: "Vida inesperada" },
  { word: "The Dark Knight", category: "Película", hint: "Caos y orden" },
  { word: "Avengers", category: "Película", hint: "Unión necesaria" },
  { word: "Deadpool", category: "Película", hint: "Humor distinto" },
  { word: "Logan", category: "Película", hint: "Despedida dura" },
  { word: "Thor", category: "Película", hint: "Poder divino" },
  { word: "Iron Man", category: "Película", hint: "Genio y ego" },
  { word: "Hulk", category: "Película", hint: "Fuerza descontrolada" },
  { word: "Black Panther", category: "Película", hint: "Reino oculto" },
  { word: "Doctor Strange", category: "Película", hint: "Realidad alterada" },
  { word: "Ant-Man", category: "Película", hint: "Tamaño relativo" },
  { word: "Minions", category: "Película", hint: "Caos divertido" },
  { word: "Inside Out", category: "Película", hint: "Emociones visibles" },
  { word: "Wall-E", category: "Película", hint: "Soledad tecnológica" },
  { word: "Ratatouille", category: "Película", hint: "Talento inesperado" },
  { word: "Brave", category: "Película", hint: "Decisiones valientes" },
  { word: "Encanto", category: "Película", hint: "Familia especial" },

  // ⚽ Deportes (40)
  { word: "Fútbol", category: "Deporte", hint: "Muy popular" },
  { word: "Baloncesto", category: "Deporte", hint: "Altura ayuda" },
  { word: "Tenis", category: "Deporte", hint: "Duelo directo" },
  { word: "Natación", category: "Deporte", hint: "Sin contacto con el suelo" },
  { word: "Boxeo", category: "Deporte", hint: "Resistencia mental" },
  { word: "Golf", category: "Deporte", hint: "Precisión sobre fuerza" },
  { word: "Rugby", category: "Deporte", hint: "Contacto constante" },
  { word: "Atletismo", category: "Deporte", hint: "Base de muchos deportes" },
  { word: "Ciclismo", category: "Deporte", hint: "Resistencia prolongada" },
  { word: "Surf", category: "Deporte", hint: "Depende del entorno" },
  { word: "Esquí", category: "Deporte", hint: "Condiciones específicas" },
  { word: "Voleibol", category: "Deporte", hint: "No puede caer" },
  { word: "Hockey", category: "Deporte", hint: "Se juega rápido" },
  { word: "Karate", category: "Deporte", hint: "Control del cuerpo" },
  { word: "Judo", category: "Deporte", hint: "Uso del equilibrio" },
  { word: "Béisbol", category: "Deporte", hint: "Turnos alternos" },
  { word: "Escalada", category: "Deporte", hint: "Superar alturas" },
  { word: "Remo", category: "Deporte", hint: "Trabajo en equipo" },
  { word: "Patinaje", category: "Deporte", hint: "Deslizamiento constante" },
  { word: "Triatlón", category: "Deporte", hint: "Cambio de ritmo" },
  { word: "Snowboard", category: "Deporte", hint: "Equilibrio en nieve" },
  { word: "Parkour", category: "Deporte", hint: "Movimiento urbano" },
  { word: "Crossfit", category: "Deporte", hint: "Alta intensidad" },
  { word: "Gimnasia", category: "Deporte", hint: "Control corporal" },
  { word: "Halterofilia", category: "Deporte", hint: "Levantar peso" },
  { word: "Boxeo tailandés", category: "Deporte", hint: "Golpes variados" },
  { word: "Esgrima", category: "Deporte", hint: "Precisión y reflejos" },
  { word: "Badminton", category: "Deporte", hint: "Ligero y rápido" },
  { word: "Squash", category: "Deporte", hint: "Espacio cerrado" },
  { word: "Motociclismo", category: "Deporte", hint: "Velocidad extrema" },
  { word: "Automovilismo", category: "Deporte", hint: "Control total" },
  { word: "Boxeo olímpico", category: "Deporte", hint: "Más técnico" },
  { word: "Kickboxing", category: "Deporte", hint: "Mezcla de estilos" },
  { word: "Taekwondo", category: "Deporte", hint: "Patadas rápidas" },
  { word: "Lucha libre", category: "Deporte", hint: "Agarres constantes" },
  { word: "Waterpolo", category: "Deporte", hint: "En agua y equipo" },
  { word: "Cricket", category: "Deporte", hint: "Popular en otros lugares" },
  { word: "Handball", category: "Deporte", hint: "Balón en mano" },
  { word: "Softball", category: "Deporte", hint: "Variante conocida" },
  { word: "Pádel", category: "Deporte", hint: "En auge reciente" }

];

module.exports = wordLibrary;